version: "3.1"
services:
    www:
        build: .
        ports: 
            - "8005:80"
        volumes:
            - ./magento2:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: magento2
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: dbpass
            MYSQL_ROOT_PASSWORD: @pass123 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
volumes:
    persistent:
